apiVersion: apps/v1
kind: Deployment
metadata:
  name: "testdeploy"
  labels:
    app: "testpo"

spec:
  replicas: 1
  selector:
    matchLabels:
      app: testpo
  template:
     metadata:
      labels:
        app: testpo
     spec:
      volumes:
      - name: mypod-pvc
        persistentVolumeClaim:
         claimName: mypvc
      containers:
      - name: "testcon1"
        image: "vimal13/apache-webserver-php"
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: mypod-pvc
