apiVersion: v1
kind: ReplicationController
metadata:
  name: testrc
spec:
  replicas: 10
  selector:
    app: test
  template:
    metadata:
      labels:
         app: test
    spec:
     containers:
       - name: testcon1
         image: vimal13/apache-webserver-php




